/*****************************************************************
 * Source file : syscall.idl
 * Platform    : V4 IA32
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.1.0 (roadrunner) on 26/06/2008 13:16
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#include <idl4glue.h>
#include "syscall-server.h"

/* Interface syscall */

IDL4_INLINE L4_Word_t syscall_ThreadControl_implementation(CORBA_Object _caller, const L4_ThreadId_t *dest, const L4_ThreadId_t *SpaceSpecifier, const L4_ThreadId_t *scheduler, const L4_ThreadId_t *pager, const void *UtcbLocation, idl4_server_environment *_env)

{
  L4_Word_t __retval = 0;

  /* implementation of IF_SYSCALL::ThreadControl */
  
  return __retval;
}

IDL4_PUBLISH_SYSCALL_THREADCONTROL(syscall_ThreadControl_implementation);

IDL4_INLINE L4_Word_t syscall_SpaceControl_implementation(CORBA_Object _caller, const L4_ThreadId_t *SpaceSpacifier, const L4_Word_t control, const L4_Fpage_t *KernelInterfacePageArea, const L4_Fpage_t *UtcbArea, const L4_ThreadId_t *Redirector, L4_Word_t *old_Control, idl4_server_environment *_env)

{
  L4_Word_t __retval = 0;

  /* implementation of IF_SYSCALL::SpaceControl */
  
  return __retval;
}

IDL4_PUBLISH_SYSCALL_SPACECONTROL(syscall_SpaceControl_implementation);

void *syscall_vtable_3[SYSCALL_DEFAULT_VTABLE_SIZE] = SYSCALL_DEFAULT_VTABLE_3;
void *syscall_vtable_discard[SYSCALL_DEFAULT_VTABLE_SIZE] = SYSCALL_DEFAULT_VTABLE_DISCARD;
void **syscall_itable[4] = { syscall_vtable_discard, syscall_vtable_discard, syscall_vtable_discard, syscall_vtable_3 };

void syscall_server(void)

{
  L4_ThreadId_t partner;
  L4_MsgTag_t msgtag;
  idl4_msgbuf_t msgbuf;
  long cnt;

  idl4_msgbuf_init(&msgbuf);
  for (cnt = 0;cnt < SYSCALL_STRBUF_SIZE;cnt++)
    idl4_msgbuf_add_buffer(&msgbuf, malloc(8000), 8000);

  while (1)
    {
      partner = L4_nilthread;
      msgtag.raw = 0;
      cnt = 0;

      while (1)
        {
          idl4_msgbuf_sync(&msgbuf);

          idl4_reply_and_wait(&partner, &msgtag, &msgbuf, &cnt);

          if (idl4_is_error(&msgtag))
            break;

          idl4_process_request(&partner, &msgtag, &msgbuf, &cnt, syscall_itable[idl4_get_interface_id(&msgtag) & SYSCALL_IID_MASK][idl4_get_function_id(&msgtag) & SYSCALL_FID_MASK]);
        }
    }
}

void syscall_discard(void)

{
}

