import "sdi/types.h";
#include <types.idl>
[uuid(IF_APPPAGER_ID)]

interface IF_APPPAGER{
  exception fileNotFound{};
  exception readError{};
  exception outOfMemory{};
  exception noPrivilege{};

  // Boot Info ELF Loader    
  void associateImage(in L4_ThreadId_t thread, in string<16> filename, out L4_Word_t initialIp)
    raises(fileNotFound, readError, outOfMemory); 

  // Copy association
  void copyAssociation(in L4_ThreadId_t fromThread, in L4_ThreadId_t toThread)
    raises(outOfMemory); 

  // Delete association
  void deleteAssociation(in L4_ThreadId_t thread);

  // Get locator
  L4_ThreadId_t getLocator();
};
// vim:sw=2:ts=2:expandtab:
