/*****************************************************************
 * Source file : ramdisk.idl
 * Platform    : V4 IA32
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.1.0 (roadrunner) on 12/09/2008 18:26
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#include <idl4glue.h>
#include "ramdisk-server.h"
#include "ramdisk.h"

// Filesystem information 
L4_BootRec_t * filesystemModule; // Grub module storing the filesystem
int            blocksize = 4096; // Size of filesystem blocks



/* Interface ramdisk */

IDL4_INLINE CORBA_long ramdisk_getBlockCount_implementation(CORBA_Object _caller, idl4_server_environment *_env)

{
  CORBA_long __retval = 0;

  /* implementation of IF_BLOCK::getBlockCount */
  
  return __retval;
}

IDL4_PUBLISH_RAMDISK_GETBLOCKCOUNT(ramdisk_getBlockCount_implementation);

IDL4_INLINE CORBA_long ramdisk_getBlockSize_implementation(CORBA_Object _caller, idl4_server_environment *_env)

{
  CORBA_long __retval = blocksize;

  /* implementation of IF_BLOCK::getBlockSize */
  
  return __retval;
}

IDL4_PUBLISH_RAMDISK_GETBLOCKSIZE(ramdisk_getBlockSize_implementation);

IDL4_INLINE void ramdisk_readBlock_implementation(CORBA_Object _caller, const L4_Word_t blockNr, buffer_t *buffer, idl4_server_environment *_env)

{
  /* implementation of IF_BLOCK::readBlock */
  
  // Copy block to buffer  
  memcpy(buffer, filesystemModule + (blocksize * blockNr), blocksize);

  return;
}

IDL4_PUBLISH_RAMDISK_READBLOCK(ramdisk_readBlock_implementation);

IDL4_INLINE void ramdisk_writeBlock_implementation(CORBA_Object _caller, const L4_Word_t blockNr, const buffer_t *buffer, idl4_server_environment *_env)

{
  /* implementation of IF_BLOCK::writeBlock */
  
  // Copy buffer to block
  memcpy(filesystemModule + (blocksize * blockNr), buffer, blocksize);

  return;
}

IDL4_PUBLISH_RAMDISK_WRITEBLOCK(ramdisk_writeBlock_implementation);

void *ramdisk_vtable_9[RAMDISK_DEFAULT_VTABLE_SIZE] = RAMDISK_DEFAULT_VTABLE_9;
void *ramdisk_vtable_discard[RAMDISK_DEFAULT_VTABLE_SIZE] = RAMDISK_DEFAULT_VTABLE_DISCARD;
void **ramdisk_itable[16] = { ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_9, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard, ramdisk_vtable_discard };

void ramdisk_server(L4_BootRec_t * fsModule)

{
  filesystemModule = fsModule;

  L4_ThreadId_t partner;
  L4_MsgTag_t msgtag;
  idl4_msgbuf_t msgbuf;
  long cnt;

  idl4_msgbuf_init(&msgbuf);
  for (cnt = 0;cnt < RAMDISK_STRBUF_SIZE;cnt++)
    idl4_msgbuf_add_buffer(&msgbuf, malloc(8000), 8000);

  while (1)
    {
      partner = L4_nilthread;
      msgtag.raw = 0;
      cnt = 0;

      while (1)
        {
          idl4_msgbuf_sync(&msgbuf);

          idl4_reply_and_wait(&partner, &msgtag, &msgbuf, &cnt);

          if (idl4_is_error(&msgtag))
            break;

          idl4_process_request(&partner, &msgtag, &msgbuf, &cnt, ramdisk_itable[idl4_get_interface_id(&msgtag) & RAMDISK_IID_MASK][idl4_get_function_id(&msgtag) & RAMDISK_FID_MASK]);
        }
    }
}

void ramdisk_discard(void)

{
}

